import type { StoreData } from "../domain/types.js";

const now = "2026-05-27T00:00:00.000Z";

export const seedData: StoreData = {
  users: [
    {
      id: "u-admin",
      email: "admin@faazhi.local",
      password: "Admin123!",
      name: "Dr. Aisha Rahman",
      role: "admin",
      avatarColor: "hsl(218 65% 22%)",
      enrolledSubjectIds: [],
      createdAt: now,
    },
    {
      id: "u-student-1",
      email: "student1@faazhi.local",
      password: "Student123!",
      name: "Priya Shah",
      role: "student",
      avatarColor: "hsl(38 75% 52%)",
      centreNumber: "GB123",
      candidateNumber: "0042",
      enrolledSubjectIds: ["9618", "9709"],
      createdAt: now,
    },
    {
      id: "u-student-2",
      email: "student2@faazhi.local",
      password: "Student123!",
      name: "Liam Carter",
      role: "student",
      avatarColor: "hsl(358 60% 50%)",
      centreNumber: "GB123",
      candidateNumber: "0043",
      enrolledSubjectIds: ["9702", "9709"],
      createdAt: now,
    },
  ],
  sessions: [],
  subjects: [
    {
      id: "9618",
      code: "9618",
      name: "Computer Science",
      description: "Programming, algorithms, data representation, and systems.",
      level: "a-level",
      status: "published",
      isFree: true,
      theme: { accent: "#155EEF", canvasBackground: "#F8FBFF" },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "9709",
      code: "9709",
      name: "Mathematics",
      description: "Pure maths, mechanics, statistics, and problem-solving.",
      level: "a-level",
      status: "published",
      isFree: false,
      theme: { accent: "#0F766E", canvasBackground: "#F7FCFA" },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "9702",
      code: "9702",
      name: "Physics",
      description: "Kinematics, forces, energy, waves, and electricity.",
      level: "a-level",
      status: "published",
      isFree: false,
      theme: { accent: "#7C3AED", canvasBackground: "#FAF8FF" },
      createdAt: now,
      updatedAt: now,
    },
  ],
  papers: [
    {
      id: "paper-9618-1",
      subjectId: "9618",
      title: "Paper 1",
      description: "Theory fundamentals: information representation, hardware, networking, and databases.",
      estimatedTime: "18-22 hours",
      status: "published",
      order: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "paper-9618-2",
      subjectId: "9618",
      title: "Paper 2",
      description: "Problem solving and programming: pseudocode, trace tables, testing, validation, and file handling.",
      estimatedTime: "16-20 hours",
      status: "published",
      order: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "paper-9618-3",
      subjectId: "9618",
      title: "Paper 3",
      description: "Advanced theory: networks, databases, operating systems, security, floating-point arithmetic, and logic.",
      estimatedTime: "14-18 hours",
      status: "published",
      order: 3,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "paper-9618-4",
      subjectId: "9618",
      title: "Paper 4",
      description: "Practical programming: programming techniques, OOP, abstract data types, recursion, searching, sorting, and debugging.",
      estimatedTime: "12-16 hours",
      status: "published",
      order: 4,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "paper-9709-1",
      subjectId: "9709",
      title: "Paper 1",
      description: "Pure mathematics paper workspace.",
      estimatedTime: "10-14 hours",
      status: "published",
      order: 1,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "paper-9702-1",
      subjectId: "9702",
      title: "Paper 1",
      description: "Physics paper workspace.",
      estimatedTime: "10-14 hours",
      status: "published",
      order: 1,
      createdAt: now,
      updatedAt: now,
    },
  ],
  subjectAccess: [
    {
      id: "access-student-1-9709",
      studentId: "u-student-1",
      subjectId: "9709",
      status: "active",
      subscribedAt: now,
      currentPeriodEndsAt: "2026-06-27T00:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "access-student-2-9702",
      studentId: "u-student-2",
      subjectId: "9702",
      status: "trialing",
      trialStartedAt: now,
      trialEndsAt: "2026-06-03T00:00:00.000Z",
      updatedAt: now,
    },
  ],
  enrollments: [
    { id: "enr-1", studentId: "u-student-1", subjectId: "9618", status: "active", enrolledAt: now },
    { id: "enr-2", studentId: "u-student-1", subjectId: "9709", status: "active", enrolledAt: now },
    { id: "enr-3", studentId: "u-student-2", subjectId: "9702", status: "active", enrolledAt: now },
  ],
  lessons: [
    {
      id: "lesson-9618-pseudocode",
      subjectId: "9618",
      paperId: "paper-9618-1",
      title: "Information representation",
      description: "Binary, denary, hexadecimal, character encoding, and data storage fundamentals.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-communication",
      subjectId: "9618",
      paperId: "paper-9618-1",
      title: "Communication and internet technologies",
      description: "Networks, internet protocols, transmission, and communication concepts.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-hardware",
      subjectId: "9618",
      paperId: "paper-9618-1",
      title: "Hardware and virtual machines",
      description: "Computer architecture, hardware components, and virtual machines.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-processor",
      subjectId: "9618",
      paperId: "paper-9618-1",
      title: "Processor fundamentals",
      description: "CPU architecture, registers, instruction cycles, and addressing modes.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-system-software",
      subjectId: "9618",
      paperId: "paper-9618-1",
      title: "System software",
      description: "Operating systems, translators, utilities, and software management.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-security",
      subjectId: "9618",
      paperId: "paper-9618-1",
      title: "Security, privacy, and data integrity",
      description: "Threats, protection measures, privacy, and maintaining valid data.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-algorithms",
      subjectId: "9618",
      paperId: "paper-9618-2",
      title: "Algorithm design and problem solving",
      description: "Break problems down, design algorithms, and reason about solutions.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-pseudocode-paper-2",
      subjectId: "9618",
      paperId: "paper-9618-2",
      title: "Pseudocode and flowcharts",
      description: "Read, trace, and write Cambridge-style pseudocode and flowcharts.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-data-structures",
      subjectId: "9618",
      paperId: "paper-9618-2",
      title: "Data types and structures",
      description: "Arrays, records, files, data types, and structured storage.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-constructs",
      subjectId: "9618",
      paperId: "paper-9618-2",
      title: "Programming constructs",
      description: "Sequence, selection, iteration, procedures, and functions.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-testing",
      subjectId: "9618",
      paperId: "paper-9618-2",
      title: "Testing, validation, and verification",
      description: "Test plans, validation checks, verification, and debugging.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-file-handling",
      subjectId: "9618",
      paperId: "paper-9618-2",
      title: "File handling",
      description: "Read, write, append, search, and update file-based data.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-advanced-data",
      subjectId: "9618",
      paperId: "paper-9618-3",
      title: "Data representation and compression",
      description: "Advanced data representation, storage formats, and compression.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-advanced-networking",
      subjectId: "9618",
      paperId: "paper-9618-3",
      title: "Communication and networking",
      description: "Advanced networking models, protocols, and communication systems.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-database-modelling",
      subjectId: "9618",
      paperId: "paper-9618-3",
      title: "Database modelling and normalisation",
      description: "Entity relationships, relational design, keys, and normalisation.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-operating-systems",
      subjectId: "9618",
      paperId: "paper-9618-3",
      title: "Operating systems",
      description: "Scheduling, memory management, interrupts, and system resources.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-floating-point",
      subjectId: "9618",
      paperId: "paper-9618-3",
      title: "Floating-point arithmetic",
      description: "Representation, normalisation, precision, and arithmetic effects.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-logic",
      subjectId: "9618",
      paperId: "paper-9618-3",
      title: "Logic gates and Boolean algebra",
      description: "Truth tables, logic gates, expressions, and Boolean simplification.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-programming-techniques",
      subjectId: "9618",
      paperId: "paper-9618-4",
      title: "Programming techniques",
      description: "Write structured, readable, and maintainable practical programs.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-oop",
      subjectId: "9618",
      paperId: "paper-9618-4",
      title: "Object-oriented programming",
      description: "Classes, objects, inheritance, encapsulation, and methods.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-adts",
      subjectId: "9618",
      paperId: "paper-9618-4",
      title: "Abstract data types",
      description: "Stacks, queues, linked lists, trees, and ADT operations.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-recursion",
      subjectId: "9618",
      paperId: "paper-9618-4",
      title: "Recursion",
      description: "Recursive thinking, base cases, and tracing recursive calls.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-search-sort",
      subjectId: "9618",
      paperId: "paper-9618-4",
      title: "Searching and sorting",
      description: "Linear search, binary search, bubble sort, insertion sort, and efficiency.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9618-debugging",
      subjectId: "9618",
      paperId: "paper-9618-4",
      title: "Practical debugging and refinement",
      description: "Find, explain, and fix errors in practical programming tasks.",
      status: "published",
      estimatedMinutes: 18,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9709-gradients",
      subjectId: "9709",
      paperId: "paper-9709-1",
      title: "Gradient means velocity",
      description: "Connect distance-time graphs to motion.",
      status: "published",
      estimatedMinutes: 12,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "lesson-9702-kinematics",
      subjectId: "9702",
      paperId: "paper-9702-1",
      title: "Displacement-time graphs",
      description: "Interpret gradient and motion from graph shapes.",
      status: "published",
      estimatedMinutes: 14,
      createdAt: now,
      updatedAt: now,
    },
  ],
  scenes: [
    {
      id: "scene-9618-1",
      lessonId: "lesson-9618-pseudocode",
      title: "Sequence and selection",
      type: "concept",
      status: "published",
      order: 1,
      durationSeconds: 45,
      animation: "fade",
      background: "#F8FBFF",
    },
    {
      id: "scene-9709-1",
      lessonId: "lesson-9709-gradients",
      title: "Gradient means velocity",
      type: "concept",
      status: "published",
      order: 1,
      durationSeconds: 72,
      animation: "fade",
      background: "#F7FCFA",
    },
    {
      id: "scene-9702-1",
      lessonId: "lesson-9702-kinematics",
      title: "Displacement-time graphs",
      type: "concept",
      status: "published",
      order: 1,
      durationSeconds: 72,
      animation: "fade",
      background: "#FAF8FF",
    },
  ],
  blocks: [
    {
      id: "block-9618-1",
      sceneId: "scene-9618-1",
      type: "paragraph",
      content: "Pseudocode is a planning language. It shows the logic before we worry about exact syntax.",
      alignX: "center",
      alignY: "middle",
      stepIndex: 1,
      startTime: 0,
      duration: 10,
      animation: "fade",
      order: 1,
    },
    {
      id: "block-9618-2",
      sceneId: "scene-9618-1",
      type: "code",
      content: "INPUT mark\nIF mark >= 50 THEN\n  OUTPUT \"Pass\"\nELSE\n  OUTPUT \"Try again\"\nENDIF",
      language: "pseudocode",
      alignX: "center",
      alignY: "middle",
      stepIndex: 2,
      startTime: 8,
      duration: 20,
      animation: "fade",
      order: 2,
    },
    {
      id: "block-9709-1",
      sceneId: "scene-9709-1",
      type: "keyIdea",
      content: "Gradient tells us the rate of change.",
      alignX: "center",
      alignY: "middle",
      stepIndex: 1,
      startTime: 0,
      duration: 15,
      animation: "fade",
      order: 1,
    },
    {
      id: "block-9702-1",
      sceneId: "scene-9702-1",
      type: "list",
      content: "",
      items: ["Steeper line means greater speed", "Flat line means stationary", "Downward slope means returning"],
      listKind: "bullet",
      alignX: "center",
      alignY: "middle",
      stepIndex: 1,
      startTime: 0,
      duration: 20,
      animation: "fade",
      order: 1,
    },
  ],
  narration: [],
  progress: [],
  workspaces: [],
  accountSettings: {
    productName: "Faazhi",
    supportEmail: "support@faazhi.local",
    defaultStudentTheme: "bright-focus",
  },
};
